version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.4.4
    working_directory: ~/app
    steps:
      - checkout

      - setup_remote_docker:
          reusable: true

      - type: shell
        name: Install build tools
        command: mix do local.hex --force, local.rebar --force

      - type: cache-restore
        key: mix.lock-{{checksum "mix.lock"}}

      - type: shell
        name: Fetch dependencies
        command: mix deps.get

      - type: shell
        name: Compile dependencies
        command: mix deps.compile

      - type: cache-save
        key: mix.lock-{{checksum "mix.lock"}}
        paths:
          - _build
          - deps

      - type: shell
        name: Build release
        command: mix docker.build

      - type: shell
        name: Build image
        command: mix docker.release

      - type: shell
        name: Login to Docker
        command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - type: shell
        name: Build release
        command: mix docker.publish
